# Generated by Django 5.0.7 on 2024-08-13 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='music_list', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
