# Generated by Django 5.0.7 on 2024-08-13 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_music_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Music',
        ),
    ]
