# Generated by Django 5.0.7 on 2024-08-13 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='music/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
